Select "Gender" 
from customer as c
limit 20

--What is the total revenue generated by male vs. female customers?
Select "Gender", SUM(purchase_amount) as revenue
from customer
group by "Gender";

--Which customer used a discount but still spent more than the avg purchase amount?
Select "Customer_ID", purchase_amount
from customer
where "Discount_Applied"='Yes' and purchase_amount>=(SELECT Avg(purchase_amount) from customer);

--which are the top 5 products with the highest avg review_rating?
select "Item_Purchased", 
ROUND(100*SUM(CASE WHEN "Discount_Applied"='Yes' THEN 1 ELSE 0 END) /COUNT(*),2) as discount_rate
from customer
group by "Item_Purchased"
order by discount_rate desc
limit 5;


--Segment customers into new, returning and loyal based on thier total no of previous purchases
--and show the count of each segment 
with "Customer_Type" as (
SELECT "Customer_ID", "Previous_Purchases",
CASE 
    WHEN "Previous_Purchases"=1 THEN 'NOW'
    WHEN "Previous_Purchases" BETWEEN 2 and 10 THEN 'Returning'
    Else 'Loyal'
    END as "Customer_Segment"
from customer
)
SELECT "Customer_Segment", COUNT(*) as "Number of customers"
from "Customer_Type"
group by "Customer_Segment";

--What are the Top 3 most purchased products within each category?
with Item_Counts as (
SELECT "Category", "Item_Purchased",
COUNT("Customer_ID") as total_orders,
ROW_NUMBER() over (partition by "Category" order by COUNT("Customer_ID") DESC ) as item_rank
from customer
group by "Category", "Item_Purchased"
)
Select item_rank, "Category", "Item_Purchased", total_orders
from item_counts
where item_rank<=3;

--Are customers who are repeat buyers also likely to subscribe?
select "Subscription_Status",
Count("Customer_ID") as repeat_buyers
from customer
where "Previous_Purchases">5
group by "Subscription_Status";

--What is the revenue contribution of each age group?
Select "age_group",
Sum(purchase_amount) as total_revenue
from customer
group by "age_group"
order by total_revenue DESC;

